// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBC1YnBQaOAAJRic1Bpf6BsZEzkDo4Rt0',
    appId: '1:935557741201:android:fb44a449f8dac62c4c1d30',
    messagingSenderId: '935557741201',
    projectId: 'flutter-firebase-ebeb3',
    databaseURL: 'https://flutter-firebase-ebeb3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-firebase-ebeb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzvdhzdjyConPUtXgUcJ7Bw7J5IyQKNcI',
    appId: '1:935557741201:ios:6c3b8bfe26825cde4c1d30',
    messagingSenderId: '935557741201',
    projectId: 'flutter-firebase-ebeb3',
    databaseURL: 'https://flutter-firebase-ebeb3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-firebase-ebeb3.appspot.com',
    iosClientId: '935557741201-e1n5mrk0rac4fa5134ifk08ls5hrke5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
